[[redirects]]
  from = "/COMP4537/labs/4/search.html"
  to = "/search.html"
  status = 301
  force = true


[[redirects]]
  from = "/COMP4537/labs/4/store.html"
  to = "/store.html"
  status = 301
  force = true